[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
